server:
  port: ${PORT:8998}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    non-secure-port: ${PORT:8998}
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/registry/

spring:
  application:
     name: hystrix-dashboard-service



