server:
  port: ${PORT:8762}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/

# custom attribute for the actuator info endpoint
info:
  app:
    name: circuit-breaker

# give the application a name
spring:
  application:
    name: circuit-breaker

management:
  security:
    enabled: false

logging:
  level:
      - ".=info"
      - "com.apascualco.microservices=debug"
      - "org.springframework=info"